# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hello.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bhello.proto\x12\x05hello\" \n\x12HelloWorldResponse\x12\n\n\x02id\x18\x01 \x01(\t\"\x1f\n\x11HelloWorldRequest\x12\n\n\x02id\x18\x01 \x01(\t2L\n\x05Hello\x12\x43\n\nprintHello\x12\x18.hello.HelloWorldRequest\x1a\x19.hello.HelloWorldResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hello_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_HELLOWORLDRESPONSE']._serialized_start=22
  _globals['_HELLOWORLDRESPONSE']._serialized_end=54
  _globals['_HELLOWORLDREQUEST']._serialized_start=56
  _globals['_HELLOWORLDREQUEST']._serialized_end=87
  _globals['_HELLO']._serialized_start=89
  _globals['_HELLO']._serialized_end=165
# @@protoc_insertion_point(module_scope)
